### ISSUE TITLE
Add ResStock 3.2 ASHP parameters

### ISSUE THREAD

**Issue by mnblonsky** [NREL/OCHRE#128]
I'm running models from ResStock 2024 (v3.2.0) with ASHP upgrades, and getting the following errors:

 - `ochre.utils.base.OCHREException: Cannot find multispeed parameters for 9.2 HSPF MSHP Heater`
 - `ochre.utils.base.OCHREException: Cannot find multispeed parameters for 11.0 HSPF ASHP Heater`
 - `ochre.utils.base.OCHREException: Unknown inputs for HVAC Heating efficiency: {'Units': 'COP', 'Value': 4.0}`

I'm not sure which errors align with which upgrades, but I think we should get these incorporated soon if we can.

@jmaguire1 - is this something you can add quickly, or does this involve deeper changes to the ASHP modeling?

**Comment by jmaguire1** [comment]
@mnblonsky: Adding new ASHP or MSHP options shouldn't be a big lift. I can do that in a few hours, although I'd want to review what's in ResStock and make sure we cover all possible options, even if we didn't hit them in this run.

For the HVAC with COP, was that a GSHP? AFAIK that's the only piece of HVAC equipment we use COP rather than HSPF (because there is a different test procedure for rating them), and they're a relatively recent addition into ResStock that I didn't have any intention of covering since it's a lot of work for a technology no one has been asking about.

If you have the xml files for each failure I can take a look at them and try to get you a fix later that week, if that timing works.

**Comment by mnblonsky** [comment]
Yes, the COP=4 was a GSHP, let's skip that one for now. The other two are related to the first two HP upgrades in ResStock 2024 (ENERGY STAR and CCHP). Note that there's a 11 HSPF ASHP and MSHP. 

I'll send xml files on Teams, let me know if I can help add the parameters in

**Comment by mnblonsky** [comment]
Addressed in #130
