### ISSUE TITLE
Same simulation keeps giving different results

### ISSUE THREAD

**Issue by phaniarvind** [NREL/OCHRE#136]
I am facing an issue with running the same building multiple times. I'm unable to figure out if it is an issue with the way I defined my building or with the input files or with my computer. Any help would be greatly appreciated. Apologies in advance if there is a trivial mistake somewhere.

Attached is a zip folder that contains a script that will define a building by generating arguments for it and simulate the exact same building ten times. At the end the metrics for each are collected and printed. The problem is that the metrics are all different.

[BaselineTest.zip](https://github.com/user-attachments/files/16631014/BaselineTest.zip)

**Comment by mnblonsky** [comment]
Hi @phaniarvind, all you need to do is set the `seed` in the `dwelling_args`:

```
dwelling_args = {
    ...
    "seed": 1,
}
```

This will reset the random number generator, which impacts a few things like initial starting temperatures and EV charging events. Normally the seed is set based on the `output_path`, but since you don't specify one then it doesn't get set.

I think our documentation of this is wrong, sorry about that. We'll try to get it fixed soon.

**Comment by phaniarvind** [comment]
Ah gotcha! I was wondering if there's any random number selection involved but I didn't think of this in particular. Sorry about that. Thanks a lot for your time and patience! It works now.
