### ISSUE TITLE
A ValueError when running the simple example 

### ISSUE THREAD

**Issue by xiaofeiwang158** [NREL/OCHRE#83]
Hello, 

When I was running the simple example, I met the following error. Do you know how to solve it? 

Thanks,
Xiaofei

File [c:\Users\xwang3\AppData\Local\anaconda3\envs\EVResilience\lib\site-packages\psychrolib.py:700](file:///C:/Users/xwang3/AppData/Local/anaconda3/envs/EVResilience/lib/site-packages/psychrolib.py:700), in GetHumRatioFromRelHum(TDryBulb, RelHum, Pressure)
    684 def GetHumRatioFromRelHum(TDryBulb: float, RelHum: float, Pressure: float) -> float:
    685     """
    686     Return humidity ratio given dry-bulb temperature, relative humidity, and pressure.
    687 
   (...)
    698 
    699     """
--> 700     if RelHum < 0 or RelHum > 1:
    701         raise ValueError("Relative humidity is outside range [0, 1]")
    703     VapPres = GetVapPresFromRelHum(TDryBulb, RelHum)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by mnblonsky** [comment]
Hi, yes I've seen this before. It's an issue with numba and numpy. I would try uninstalling and reinstalling both. I've seen having multiple versions of numpy installed cause this error too. Try running `import numba`, if that works, then OCHRE should work too.

@jmaguire1 We have numba as a required dependency, but we never import it directly. It's only indirectly imported through psyrchrolib, where it's an optional dependency. We should do a direct import so that the error is more obvious. I can work on that soon.

**Comment by xiaofeiwang158** [comment]
Thanks very much for the quick response. 
numba requires numpy 1.25 or less, I've downgraded numpy and the issue is solved. Now OCHRE works well. 

Best,
Xiaofei

**Comment by mnblonsky** [comment]
Addressed in commit on 10/17, no PR
